name: Kyosk GUI

on:
  push:
    branches: 
      - main
jobs:

    docker:
      name:  Docker Build and Publish
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
    
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
    
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
          - name: Get branch name
            id: get_branch
            run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    
          - if: ${{ github.ref == 'refs/heads/main' }}
            name: Build and push Docker image for frontend
            run: |
              docker build -t ${{ vars.DOCKERHUB_USERNAME }}/kyoskfront:latest .
              docker push ${{ vars.DOCKERHUB_USERNAME }}/kyoskfront:latest    
