name: Kyosk GUI

on:
  push:
    branches: 
      - main
jobs:

    docker:
      name:  Docker Build and Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: Install Dependencies  
          run: npm install --legacy-peer-deps
        - name: Build Application  
          run: npm run build --if-present

        - name: Checkout Repo
          uses: actions/checkout@v4
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
    
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
    
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
        - name: Get branch name
          id: get_branch
          run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    
        - if: ${{ github.ref == 'refs/heads/main' }}
          name: Build and push Docker image for frontend
          run: |
              docker build -t ${{ vars.DOCKERHUB_USERNAME }}/kyoskfrontend:latest .
              docker push ${{ vars.DOCKERHUB_USERNAME }}/kyoskfrontend:latest    
